# Generated by Django 5.0.1 on 2024-02-07 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('reads', models.IntegerField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computer_cat', to='myapp.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='language_cat', to='myapp.language')),
            ],
        ),
    ]
