# Generated by Django 5.0.1 on 2024-02-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_books_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='language',
        ),
        migrations.AddField(
            model_name='books',
            name='lang',
            field=models.ManyToManyField(blank=True, related_name='language_cat', to='myapp.language'),
        ),
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
