# Generated by Django 5.0.1 on 2024-02-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
