# Generated by Django 5.0.1 on 2024-01-31 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_category_student_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.category'),
        ),
    ]
